### ISSUE TITLE
Multiple doc selection on sharepoint does not work with large selections

### ISSUE THREAD

**Issue by mhaack** [adobe/helix-sidekick-extension#228]
**Description**
Selecting multiple documents for preview/publish on Sharepoint does not work with large selection sets

**To Reproduce**
See Screenshot:
![Screenshot 2023-01-12 at 15 16 45](https://user-images.githubusercontent.com/2643450/212092087-a43ccb26-a3e0-47a8-a4f5-696b7d90e6cd.png)

**Comment by rofe** [comment]
I've noticed it, too. This is due to the fact that we currently rely on DOM elements with `aria-selected="true"` attributes to collect selected files, but SharePoint optimizes the number of elements it is keeping in the DOM when large lists are being scrolled through, I assume due to performance. It must be keeping the actual selection in memory somewhere, but I doubt there's an easy way to access it from "outside".

For now, I consider this a known issue.

**Comment by rofe** [comment]
Closing as a known issue for now. We can reopen if a solution emerges.

**Comment by synox** [comment]
It this known-issue documented in the docs? What is the workaround?

**Comment by rofe** [comment]
@synox I documented the limitation here now: https://www.hlx.live/docs/sidekick#bulk-actions
The workaround is to preview/publish a large amount of files in smaller badges.

There is currently no known way to fix this, but I'll leave the issue open to encourage contributions from the wider community.

**Comment by rofe** [comment]
FYI, @ravkiran found out that you get a higher amount of selected items in tiles view (up to ~250), which could help make the workaround to preview/publish in batches a bit less painful.
