### ISSUE TITLE
502 on new documents

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-sidekick-extension#55]
I think the flow is like this:
- open the sidekick on an existing page
- go to Sharepoint, create a new document
- edit the document, rename it
- hit the "Preview" button

-> nothing happens

The admin requests go to `/document` while the document has now a different name. See screenshot:

![image](https://user-images.githubusercontent.com/474200/157420384-49b9d664-042b-4ee2-ae89-6f9e88f8a3db.png)

**Comment by rofe** [comment]
This is a tricky problem and not limited to new documents, but more generally renamed documents: Word doesn't update the URL after renaming a document, so it will be a challenge for the Sidekick to find out when to refetch the status. What happens:
1. User creates new Word document or opens existing one (let's call it `a`)
2. Sidekick opens automatically based on global state (or user opens it manually)
3. Sidekick fetches status for current `editUrl` -> will resolve in a resource path ending with `/a`
4. User renames document to `b`, leaving Sidekick clueless
5. User clicks Preview -> Sidekick tries to preview path with `/a` instead of `/b` -> error from admin API

The only way I see to prevent this would be for the Sidekick to refetch the status periodically while open on an the editor, but depending on the interval it might still not always catch a document rename, and would put significantly more load on the admin API...

@tripodsan do you have an idea how to handle this case?

**Comment by rofe** [comment]
Side note: the `502` is a bit unexpected in my opinion. Based on the [API docs](https://www.hlx.live/docs/admin.html#tag/preview) I would probably expect a `400` or `404`...

**Comment by tripodsan** [comment]
it would be possible to POST via editUrl, so it would be computed again. eg:

`POST /preview/owner/repo/ref?editUrl=https://adobe.sharepoint.com/....`

idk, if this is already supported by admin.

---

>  Side note: the 502 is a bit unexpected in my opinion. Based on the [API docs](https://www.hlx.live/docs/admin.html#tag/preview) I would probably expect a 400 or 404

I agree. it should be a `404`

**Comment by rofe** [comment]
Fixed by https://github.com/adobe/helix-sidekick/pull/327
