### ISSUE TITLE
Improve help UX

### ISSUE THREAD

**Issue by rofe** [adobe/helix-sidekick-extension#67]
Getting feedback that the current help UX is not intuitive enough. People have difficulty acknowledging topics ("got it!") so the same content keeps reappearing over and over. Also clicking the white dots to go to the next balloon seems to be a challenge.

I propose to add a dedicated "next" to help with navigation, and a combobox-like "close" button to dismiss the help content, letting the user choose between the following options:
- show this again later: the same help topic will be displayed again
- don't show this anymore: the same help topic will not reappear
- never show any help content: opt out of all help topics

**Comment by rofe** [comment]
cc @kptdobe @tripodsan

**Comment by rofe** [comment]
<img width="259" alt="image" src="https://user-images.githubusercontent.com/1609742/159435060-18f4188d-9091-4a8d-b647-9e296e246625.png">

**Comment by kptdobe** [comment]
Yeah... thanks! I will finally be able to get rid of those blue balloons ;)
The difference between 2 and 3 is not obvious: "Don't show help topic again" should be read as "Don't show this help topic again", otherwise it is confusing. But to make it more simple, I do not think that people need those 2 options: I would merge them into "Never show any help topics". Either should look at it later or never but not later except the current one.
