### ISSUE TITLE
Advertise new sidekick

### ISSUE THREAD

**Issue by rofe** [adobe/helix-sidekick-extension#802]
Sidekick should tell users about the new Sidekick extension (v7) once available:
![image](https://github.com/user-attachments/assets/c7b19570-9953-417e-95a2-f0697fd48e50)

Sidekick should show this dialog if:
- new extension is not installed yet
- user clicked "later" more than a week ago (after a grace period, this may be shortened to 2 days, then 1 day...)

**Comment by amol-anand** [comment]
If they clicked on 'Later', I would give it a week before popping up again unless we want to be aggressively pushing them to switch to the new sidekick. 😄 
Once a day could be borderline annoying. If the goal is to switch everyone quickly, I'm ok with this, otherwise I would be start with once a week and then ramp up the frequency as we have majority of the population on the new sidekick. 

Separately, we should also share the new sidekick link with our VIP customers in their respective channels.
